/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ${{VAR_NAMESPACE_UNDERSCORE}}_StringComparator */

#ifndef _Included_${{VAR_NAMESPACE_UNDERSCORE}}_StringComparator
#define _Included_${{VAR_NAMESPACE_UNDERSCORE}}_StringComparator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ${{VAR_NAMESPACE_UNDERSCORE}}_StringComparator
 * Method:    printTextNative0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_${{VAR_NAMESPACE_UNDERSCORE}}_StringComparator_printTextNative0
  (JNIEnv *, jobject);

/*
 * Class:     ${{VAR_NAMESPACE_UNDERSCORE}}_StringComparator
 * Method:    compareNative0
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_${{VAR_NAMESPACE_UNDERSCORE}}_StringComparator_compareNative0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
