###############################################################################
#                                                                             #
#     Docker image to build and test the ${{VAR_PROJECT_NAME}} project
#                                                                             #
###############################################################################
FROM ubuntu:20.04

# Arguments
ARG DWORKDIR="/app"
ARG DEBIAN_FRONTEND=noninteractive

# Environment
ENV TZ=UTC

# Working directory
WORKDIR $DWORKDIR

# APT dependencies
RUN apt-get -y update && apt-get -y --no-install-recommends install \
 build-essential \
 cmake \
 git \
 ca-certificates

# Volumes: include the entire source tree
VOLUME ["$DWORKDIR"]

ENTRYPOINT [".docker/entrypoint.sh"]

CMD ["build"]
