###############################################################################
#                                                                             #
#     Docker image to build and test the ${{VAR_PROJECT_NAME}} project
#                                                                             #
###############################################################################
FROM python:3.13-bookworm

# Arguments
ARG UID=0
ARG GID=0
ARG DWORKDIR="/${{VAR_PROJECT_NAME_LOWER}}"

# Working directory
WORKDIR "$DWORKDIR"

# The build dependencies must be part of the image
COPY requirements.txt "$DWORKDIR"

# Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Conditionally add regular user and his primary group.
# If both the GID and UID build arguments were specified to be non-zero,
# a separate regular user and group named 'user' are created with those IDs.
# This makes sense with non-rootless Docker, in which case using root inside
# a container is discouraged.
# However, when using rootless Docker, a separate regular user is not required
# so if GID or UID is zero, the user and group are not added.
RUN if [ $GID -ne 0 ] && [ $UID -ne 0 ]; then \
  addgroup --gid $GID user && \
  adduser --uid $UID --gid $GID --disabled-password --gecos '' user; \
 fi

# Use the user with the specified UID and GID
USER $UID:$GID

# Volumes: include the entire source tree
VOLUME ["$DWORKDIR"]

ENTRYPOINT [".docker/entrypoint.sh"]

CMD ["build"]
