###############################################################################
#                                                                             #
#     Docker image to build and test the ${{VAR_PROJECT_NAME}} project
#                                                                             #
###############################################################################
FROM r-base:4.2.2

# Arguments
ARG UID=0
ARG GID=0
ARG DWORKDIR="/${{VAR_PROJECT_NAME_LOWER}}"

# Environment
ENV TZ=UTC

# APT dependencies
RUN apt-get -y update && apt-get -y install \
 openssl \
 libssl-dev \
 libcurl4-openssl-dev \
 libssh2-1-dev \
 libxml2-dev \
 zlib1g-dev \
 libbz2-dev \
 liblzma-dev \
 libpng-dev \
 libtiff5-dev \
 libjpeg-dev \
 libharfbuzz-dev \
 libfribidi-dev \
 libfontconfig1-dev \
 libfreetype-dev

# R dependencies
RUN R -e "install.packages(c('devtools', 'Rcpp', 'testthat', 'roxygen2'), dependencies=TRUE)"

# Conditionally add regular user and his primary group.
# If both the GID and UID build arguments were specified to be non-zero,
# a separate regular user and group named 'user' are created with those IDs.
# This makes sense with non-rootless Docker, in which case using root inside
# a container is discouraged.
# However, when using rootless Docker, a separate regular user is not required
# so if GID or UID is zero, the user and group are not added.
RUN if [ $GID -ne 0 ] && [ $UID -ne 0 ]; then \
  addgroup --gid $GID user && \
  adduser --uid $UID --gid $GID --disabled-password --gecos '' user; \
 fi

# Use the user with the specified UID and GID
USER $UID:$GID

# Working directory
WORKDIR "$DWORKDIR"

# Volumes: include the entire source tree
VOLUME ["$DWORKDIR"]

ENTRYPOINT [".docker/entrypoint.sh"]

CMD ["build"]
